services:
  bot:
    build:
      context: .
    command: yarn develop
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: sync
          path: ./locales
          target: /app/locales
        - action: rebuild
          path: yarn.lock
        - action: rebuild
          path: ./locales
    env_file:
      - .env
    networks:
      - mongodb

networks:
  mongodb:
    external: true
